### ISSUE TITLE
[Week1] 수정 사항

### ISSUE THREAD

**Issue by yurim830** [AND-SOPT-iOS/KimYurim#1]
## TODO
- [x] ViewContoller와 View로 분리

- [x] 컴포넌트 추가

    **Main View**
    - [x] 전환모드 변경 버튼을 팝업 버튼으로 수정
    - [x] 산타 이미지 추가

    **Detail View**
    - [x] 배경 이미지 추가 + 투명도
    - [x] ContentLabel: AutoLayout - 높이 50 이상, backButton top anchor 보다는 위로
