### ISSUE TITLE
[Week3] 1. 카테고리 둘러보기

### ISSUE THREAD

**Issue by yurim830** [AND-SOPT-iOS/KimYurim#8]
### Todo
- [x] App 모델
- [x] AppTableViewCell
- [x] AppCollectionViewCell

### 구현해야 할 내용
- [x] 1번 섹션
  - [x] 페이지 갯수 4개
  - [x] 좌우 스크롤 가능
  - [x] **섹션 내부 기능 없음**
- [x] 2번 섹션
  - [x] 페이지 갯수 3개(앱 9개)
  - [x]  좌우 스크롤 가능
  - [x] **섹션 내부 기능 없음**
- [x] 3번 섹션
  - [x] 2번 섹션과 동일
- [x] 4번 섹션
  - [x] 페이지 갯수 3개(앱 9개)
  - [x] 좌우 스크롤 가능
  - [x] 토스 셀 선택 시 2주차 과제 ViewController로 이동
  - [x] 모두 보기 클릭 시 차트로 이동
